export const iso = (days = 0) => new Date(Date.now() + days * 86400000).toISOString();
export function seed(demo = true) {
  const plans = [
    {id:'plan-gym',name:'Gym monthly',kind:'time',price:4900,days:30,credits:0,gymAccess:true,classes:false,description:'Your space to get stronger. Unlimited gym access.'},
    {id:'plan-all',name:'All access',kind:'combined',price:8900,days:30,credits:12,gymAccess:true,classes:true,description:'The whole experience. Gym access and 12 group sessions.'},
    {id:'plan-pack',name:'10-class pack',kind:'sessions',price:12000,days:90,credits:10,gymAccess:false,classes:true,description:'Find your rhythm with 10 classes over 90 days.'}
  ];
  const names=['Sophia Martinez','James Wilson','Emma Thompson','Noah Williams','Isabella Chen','Liam Anderson','Mia Robinson','Oliver Davis','Amelia Lewis','Lucas Martin','Charlotte Clark'];
  const members=demo?names.map((name,i)=>({id:`member-${i+1}`,name,email:name.toLowerCase().replace(' ','.')+'@example.com',phone:'+1 555 010 '+String(i+10),joinedAt:iso(-i-2)})):[];
  const memberships=members.map((m,i)=>({id:`membership-${i+1}`,memberId:m.id,planId:i%3===0?'plan-all':i%3===2?'plan-pack':'plan-gym',planName:plans[i%3===0?1:i%3===2?2:0].name,kind:plans[i%3===0?1:i%3===2?2:0].kind,gymAccess:i%3!==2,classes:i%3!==1,days:i%3===2?90:30,credits:i%3===0?12:i%3===2?10:0,status:i===2||i===8?'pending':'active',startsAt:iso(-10),endsAt:iso(i===3?-1:20),createdAt:iso(-i-2)}));
  const payments=memberships.map((m,i)=>({id:`payment-${i+1}`,memberId:m.memberId,membershipId:m.id,description:m.planName,amount:plans.find(p=>p.id===m.planId).price,currency:'USD',method:i%2?'online':'cash',status:m.status==='pending'?'pending':'paid',createdAt:iso(-i),paidAt:m.status==='pending'?null:iso(-i)}));
  const schedule=demo?['Strength & conditioning','Pilates flow','HIIT circuit','Mobility & recovery'].map((title,i)=>{const date=new Date();date.setHours([9,12,17,19][i],i===1?30:0,0,0);if(date<Date.now())date.setDate(date.getDate()+1);return{id:`class-${i+1}`,title,trainerId:['trainer-1','trainer-2','trainer-3','trainer-2'][i],startsAt:date.toISOString(),duration:50,capacity:[12,10,16,12][i],type:'Group class',room:['Studio A','Studio B','Training floor','Studio B'][i]};}):[];
  return {passwordResets:[],invitations:[],auditLogs:[],notifications:[],settings:{name:'Forma Training Club',currency:'USD',timezone:'Africa/Casablanca',email:'hello@forma.example',cancellationHours:4},plans,members,memberships,payments,schedule,bookings:[],attendance:demo?members.slice(0,2).map((m,i)=>({id:`visit-${i}`,memberId:m.id,createdAt:iso()})):[],users:demo?[{id:'owner',name:'Alex Morgan',email:'owner@forma.example',role:'owner'},{id:'reception',name:'Jamie Parker',email:'reception@forma.example',role:'receptionist'},{id:'trainer-1',name:'Ethan Cole',email:'ethan@forma.example',role:'trainer'},{id:'trainer-2',name:'Olivia Bennett',email:'olivia@forma.example',role:'trainer'},{id:'trainer-3',name:'Marcus Reed',email:'marcus@forma.example',role:'trainer'},{id:'member-user',name:members[0].name,email:members[0].email,role:'member',memberId:members[0].id}]:[]};
}
