import {locale,number} from "../i18n";
import {useTranslation} from 'react-i18next';
import {useEffect,useState} from 'react';
import {api} from '../api';
import {Panel,Button,Field,Empty} from '../components/ui';
export default function Audit(){const {t}=useTranslation();
  const [query,setQuery]=useState({page:1,search:''}),[data,setData]=useState(null),[error,setError]=useState(''),[busy,setBusy]=useState(true);
  useEffect(()=>{let current=true;setBusy(true);setError('');api('/audit?'+new URLSearchParams(query)).then(d=>{if(current)setData(d);}).catch(e=>{if(current)setError(e.message);}).finally(()=>{if(current)setBusy(false);});return()=>{current=false;};},[query]);
  return <><div className="page-heading"><div><h1>{t("Audit log")}</h1><p>{t("Who changed gym records, when, and which fields changed.")}</p></div></div><Panel><form className="report-filters" onSubmit={e=>{e.preventDefault();setQuery({page:1,search:new FormData(e.currentTarget).get('search')});}}><Field label={t("Search activity")}><input dir="auto" name="search" maxLength={120} placeholder={t("Person, record, action, or field")}/></Field><Button disabled={busy}>{t("Search")}</Button><Button type="button" disabled={busy} onClick={()=>setQuery({...query})}>{t("Refresh")}</Button></form>{error&&<p className="form-error" role="alert">{t(error)}</p>}{busy?<Empty>{t("Loading activity…")}</Empty>:!error&&<><div className="table-scroll"><table><thead><tr><th>{t("When")}</th><th>{t("Who")}</th><th>{t("Record")}</th><th>{t("Action")}</th><th>{t("Changed fields")}</th></tr></thead><tbody>{data?.rows.map(row=><tr key={row.id}><td>{new Date(row.createdAt).toLocaleString(locale())}</td><td>{row.actorName}<small className="cell-sub">{t(row.actorRole)}</small></td><td>{t('audit.'+row.entity,{defaultValue:row.entity})}<small className="cell-sub">{row.recordId}</small></td><td>{t('audit.'+row.action,{defaultValue:row.action})}</td><td>{row.fields.map(field=>t('audit.'+field,{defaultValue:field})).join(' · ')||'—'}</td></tr>)}</tbody></table>{!data?.rows.length&&<Empty>{t("No matching activity.")}</Empty>}</div><div className="report-filters"><Button disabled={query.page===1} onClick={()=>setQuery({...query,page:query.page-1})}>{t("Previous")}</Button><span>{t('Page {{page}} · {{total}} events',{page:number(query.page),total:number(data?.total||0)})}</span><Button disabled={query.page*50>=(data?.total||0)} onClick={()=>setQuery({...query,page:query.page+1})}>{t("Next")}</Button></div></>}<p className="form-note">{t("The latest 5,000 events are retained. Tracking starts when this feature is installed. Sensitive values are never included. This is an operational history, not a tamper-proof compliance archive.")}</p></Panel></>;
}
