import {number} from "../i18n";
import {useTranslation} from 'react-i18next';
import {CalendarDays,Plus,ArrowUpRight,Users,Wallet,SquareCheck,Calendar} from 'lucide-react';
import {Panel,Button,Status,Avatar,Empty,LinkButton} from '../components/ui';
import {money,date,latestMembership} from '../api';
export function MemberRows({state,rows,onSelect}){const {t}=useTranslation();return <div className="table-scroll"><table><thead><tr><th>{t("Member")}</th><th>{t("Membership")}</th><th>{t("Status")}</th><th>{t("Joined")}</th><th><span className="sr-only">{t("Action")}</span></th></tr></thead><tbody>{rows.map(m=>{const plan=latestMembership(state,m.id);return <tr key={m.id}><td><button className="member-link" onClick={()=>onSelect(m)}><Avatar name={m.name}/><span><strong><bdi>{m.name}</bdi></strong><small><bdi>{m.email}</bdi></small></span></button></td><td><bdi>{plan?.planName||t("No plan yet")}</bdi></td><td><Status value={plan?.status||'inactive'}/></td><td>{date(m.joinedAt)}</td><td><button className="icon-button" aria-label={t('View {{name}}',{name:m.name})} onClick={()=>onSelect(m)}><ArrowUpRight size={17}/></button></td></tr>;})}</tbody></table>{!rows.length&&<Empty>{t("No members match your search.")}</Empty>}</div>;}
export function ClassList({state,items,onSelect}){const {t}=useTranslation();return <div className="class-list">{items.map(c=><button className="class-row" key={c.id} onClick={()=>onSelect(c)}><div className="class-time">{date(c.startsAt,{month:undefined,day:undefined,hour:'2-digit',minute:'2-digit',hour12:false,timeZone:state.settings.timezone})}<small>{date(c.startsAt,{timeZone:state.settings.timezone})}</small></div><div className="class-info"><strong><bdi>{c.title}</bdi></strong><span>{state.users.find(u=>u.id===c.trainerId)?.name||t("Trainer")} · {t('{{count}} min',{count:c.duration})}</span><small><bdi>{c.room}</bdi></small></div><span className="capacity">{number(c.booked)}/{number(c.capacity)}<span className="capacity-track"><i style={{width:Math.max(4,c.booked/c.capacity*100)+'%'}}/></span></span></button>)}{!items.length&&<Empty>{t("No upcoming sessions. Your schedule is clear.")}</Empty>}</div>;}
export default function Dashboard({state,navigate,open}){const {t}=useTranslation();
  const currency=state.settings.currency;const now=new Date();const monthKey=date(now,{month:'long',year:'numeric',day:undefined,timeZone:state.settings.timezone});
  const paid=state.payments.filter(p=>p.status==='paid'&&date(p.paidAt,{month:'long',year:'numeric',day:undefined,timeZone:state.settings.timezone})===monthKey);const revenue=paid.reduce((n,p)=>n+p.amount,0);
  const active=new Set(state.memberships.filter(m=>m.status==='active'&&new Date(m.startsAt)<=now).map(m=>m.memberId)).size;
  const today=state.attendance.filter(a=>date(a.createdAt,{year:'numeric',timeZone:state.settings.timezone})===date(now,{year:'numeric',timeZone:state.settings.timezone})).length;
  const upcoming=state.schedule.filter(c=>new Date(c.startsAt)>now).sort((a,b)=>new Date(a.startsAt)-new Date(b.startsAt));
  const pending=state.payments.filter(p=>p.status==='pending'&&p.method==='cash').length;
  const expired=state.members.filter(m=>latestMembership(state,m.id)?.status==='expired').length;
  const bars=Array.from({length:7},(_,i)=>{const d=new Date(Date.now()-(6-i)*86400000);return {label:date(d),value:state.payments.filter(p=>p.status==='paid'&&date(p.paidAt,{year:'numeric',timeZone:state.settings.timezone})===date(d,{year:'numeric',timeZone:state.settings.timezone})).reduce((n,p)=>n+p.amount,0)};});
  const max=Math.max(10000,...bars.map(b=>b.value));
  return <><div className="page-heading"><div><h1>{t("Your gym, at a glance.")}</h1><p>{t("A little clarity for your everyday operations.")}</p></div><div className="heading-actions"><span className="date-display"><CalendarDays size={16}/>{monthKey}</span><Button onClick={()=>open('scanQr')}><SquareCheck size={17}/>{t("Check in")}</Button><Button variant="primary" onClick={()=>open('member')}><Plus size={17}/>{t("Add member")}</Button></div></div><div className="metrics">{[[Users,t("Active members"),active,t("Current memberships")],[Wallet,t("Collected this month"),money(revenue,currency),t("Confirmed payments")],[SquareCheck,t('Check-ins today'),today,t("Across your gym")],[Calendar,t("Upcoming classes"),upcoming.length,t("Ready for your members")]].map(([Icon,label,value,caption])=><section className="metric" key={label}><div>{label}<Icon size={17}/></div><strong>{typeof value==='number'?number(value):value}</strong><small>{caption}</small></section>)}</div><div className="dashboard-grid"><Panel title={t("Revenue overview")} action={<span className="quiet">{t("Last 7 days")}</span>}><div className="chart-summary"><strong>{money(bars.reduce((n,b)=>n+b.value,0),currency)}</strong><span>{t("Payments collected")}</span></div><div className="chart" role="img" aria-label={t('Revenue by day: {{values}}',{values:bars.map(b=>b.label+' '+money(b.value,currency)).join(', ')})}><div className="chart-axis">{[max,max/2,0].map((v,i)=><span key={i}>{money(v,currency)}</span>)}</div><div className="bars">{bars.map(b=><div className="bar-column" key={b.label}><div className="bar-space"><div className="bar" style={{height:Math.max(2,b.value/max*100)+'%'}} title={money(b.value,currency)}/></div><span>{b.label}</span></div>)}</div></div></Panel><Panel title={t("Coming up next")} action={<LinkButton onClick={()=>navigate('schedule')}>{t("Schedule")}</LinkButton>}><ClassList state={state} items={upcoming.slice(0,3)} onSelect={c=>open('classDetail',c)}/></Panel><Panel title={t("Recent members")} action={<LinkButton onClick={()=>navigate('members')}>{t("View all")}</LinkButton>} className="recent-panel"><MemberRows state={state} rows={[...state.members].sort((a,b)=>new Date(b.joinedAt)-new Date(a.joinedAt)).slice(0,4)} onSelect={m=>open('memberDetail',m)}/></Panel><Panel title={t("Needs attention")}><button className="attention" onClick={()=>navigate('payments')}><strong>{number(pending)}</strong><span><b>{t("Pending cash payments")}</b><small>{t("Confirm payments received at the gym")}</small></span><ArrowUpRight size={17}/></button><button className="attention" onClick={()=>navigate('members')}><strong className={expired?'red':''}>{number(expired)}</strong><span><b>{t("Expired memberships")}</b><small>{t("Help your members keep moving")}</small></span><ArrowUpRight size={17}/></button><div className="attention-note">{t("A clear desk. A stronger community.")}</div></Panel></div></>;
}
