import {useState} from 'react';
import {Dumbbell,ArrowRight,ShieldCheck} from 'lucide-react';
import {Button,Field} from '../components/ui';
import {api,money} from '../api';
export default function Login({config,onLogin}){
  const [register,setRegister]=useState(false),[error,setError]=useState(''),[busy,setBusy]=useState(false);
  async function login(path,body){setBusy(true);setError('');try{await api(path,body);await onLogin();}catch(e){setError(e.message);}setBusy(false);}
  return <div className="login-layout"><section className="login-story"><div className="brand"><Dumbbell size={32}/><span>FORMA.</span></div><div><span className="story-rule"/><h1>More movement.<br/>Less management.</h1><p>Your members, your sessions, your gym.<br/>One space to bring it all together.</p><div className="public-plans">{config.plans.map(p=><div key={p.id}><span>{p.name}</span><strong>{money(p.price,config.settings.currency)}<small> / {p.days} days</small></strong></div>)}</div></div><span>{config.settings.name}</span></section><section className="login-form"><div><span className="overline">WELCOME TO {config.settings.name}</span><h2>{register?'Start your next chapter.':'Good to have you back.'}</h2><p>{register?'Create your member account.':'Sign in to your workspace or member portal.'}</p>{error&&<div className="form-error" role="alert">{error}</div>}<form onSubmit={e=>{e.preventDefault();login('/auth/'+(register?'register':'login'),Object.fromEntries(new FormData(e.currentTarget)));}}>{register&&<Field label="Full name"><input name="name" required autoComplete="name"/></Field>}<Field label="Email address"><input name="email" type="email" required autoComplete="email"/></Field><Field label="Password"><input name="password" type="password" required minLength={register?10:1} maxLength="128" autoComplete={register?'new-password':'current-password'}/></Field><Button variant="primary" className="full-width" disabled={busy}>{busy?'Signing in…':register?'Create account':'Sign in'}<ArrowRight size={17}/></Button></form><button className="text-button auth-toggle" onClick={()=>{setRegister(!register);setError('');}}>{register?'Already a member? Sign in':'New here? Create a member account'}</button>{config.demo&&<div className="demo-login"><strong>Explore the demo</strong><p>Sample accounts. No password needed.</p><div>{['owner','receptionist','trainer','member'].map(role=><Button key={role} disabled={busy} onClick={()=>login('/auth/demo',{role})}>{role}</Button>)}</div></div>}</div><small className="login-foot"><ShieldCheck size={14}/>Your gym. A little more connected.</small></section></div>;
}
