
import {useTranslation} from 'react-i18next';
import LanguageSwitcher from '../components/LanguageSwitcher';
import {useState} from 'react';
import {Dumbbell,ArrowRight,ShieldCheck} from 'lucide-react';
import {Button,Field} from '../components/ui';
import {api,money} from '../api';
export default function Login({config,onLogin}){const {t}=useTranslation();
  const [register,setRegister]=useState(false),[error,setError]=useState(''),[busy,setBusy]=useState(false);
  async function login(path,body){setBusy(true);setError('');try{await api(path,body);await onLogin();}catch(e){setError(e.message);}setBusy(false);}
  return <div className="login-layout"><section className="login-story"><div className="brand"><Dumbbell size={32}/><span>FORMA.</span></div><div><span className="story-rule"/><h1>{t("More movement.")}<br/>{t("Less management.")}</h1><p>{t("Your members, your sessions, your gym.")}<br/>{t("One space to bring it all together.")}</p><div className="public-plans">{config.plans.map(p=><div key={p.id}><span><bdi>{p.name}</bdi></span><strong>{money(p.price,config.settings.currency)}<small> / {t('days',{count:p.days})}</small></strong></div>)}</div></div><span>{config.settings.name}</span></section><section className="login-form"><LanguageSwitcher className="auth-language"/><div><span className="overline">{t('Welcome to {{gym}}',{gym:config.settings.name})}</span><h2>{register?t("Start your next chapter."):t("Good to have you back.")}</h2><p>{register?t("Create your member account."):t("Sign in to your workspace or member portal.")}</p>{error&&<div className="form-error" role="alert">{t(error)}</div>}<form onSubmit={e=>{e.preventDefault();login('/auth/'+(register?'register':'login'),Object.fromEntries(new FormData(e.currentTarget)));}}>{register&&<Field label={t("Full name")}><input dir="auto" name="name" required autoComplete="name"/></Field>}<Field label={t("Email address")}><input name="email" type="email" required autoComplete="email"/></Field><Field label={t("Password")}><input dir="auto" name="password" type="password" required minLength={register?10:1} maxLength="128" autoComplete={register?'new-password':'current-password'}/></Field><Button variant="primary" className="full-width" disabled={busy}>{busy?t("Signing in…"):register?t("Create account"):t("Sign in")}<ArrowRight size={17}/></Button></form>{!register&&<a className="text-button auth-toggle" href="#forgot-password">{t("Forgot password?")}</a>}<button className="text-button auth-toggle" onClick={()=>{setRegister(!register);setError('');}}>{register?t("Already a member? Sign in"):t("New here? Create a member account")}</button>{config.demo&&<div className="demo-login"><strong>{t("Explore the demo")}</strong><p>{t("Sample accounts. No password needed.")}</p><div>{['owner','receptionist','trainer','member'].map(role=><Button key={role} disabled={busy} onClick={()=>login('/auth/demo',{role})}>{t(role)}</Button>)}</div></div>}</div><small className="login-foot"><ShieldCheck size={14}/>{t("Your gym. A little more connected.")}</small></section></div>;
}
