import {locale,number} from "../i18n";
import {useTranslation} from 'react-i18next';
import {useState} from 'react';
import {Plus,Download,Check,ArrowUpRight,CalendarDays,Dumbbell,Clock,Mail,ShieldCheck} from 'lucide-react';
import {Button,Panel,Status,SearchBox,Empty,Avatar,Field} from '../components/ui';
import {money,date,latestMembership} from '../api';
import {MemberRows,ClassList} from './Dashboard';
export function PageHeading({title,subtitle,children}){const {t}=useTranslation();return <div className="page-heading"><div><h1>{title}</h1><p>{subtitle}</p></div><div className="heading-actions">{children}</div></div>;}
export function Members({state,open}){const {t}=useTranslation();
  const [search,setSearch]=useState(''),[filter,setFilter]=useState('all');const rows=state.members.filter(m=>(m.name+' '+m.email).toLowerCase().includes(search.toLowerCase())&&(filter==='all'||latestMembership(state,m.id)?.status===filter));
  return <><PageHeading title={t("Your members.")} subtitle={t("The people at the heart of your gym.")}><Button variant="primary" onClick={()=>open('member')}><Plus size={17}/>{t("Add member")}</Button></PageHeading><Panel><div className="list-toolbar"><div className="tabs">{['all','active','pending','expired'].map(f=><button key={f} onClick={()=>setFilter(f)} className={filter===f?'selected':''}>{f==='all'?t("All members"):t(f)}</button>)}</div><SearchBox value={search} onChange={setSearch}/></div><MemberRows state={state} rows={rows} onSelect={m=>open('memberDetail',m)}/><div className="table-footer">{t('members',{count:rows.length})}</div></Panel></>;
}
export function Memberships({state,open}){const {t}=useTranslation();return <><PageHeading title={state.user.role==='member'?t("Find your next step."):t("Plans that fit your members.")} subtitle={t("Gym access, class packs, and everything in between.")}>{state.user.role==='owner'&&<Button variant="primary" onClick={()=>open('plan')}><Plus size={17}/>{t("Create plan")}</Button>}</PageHeading><div className="plan-grid">{state.plans.map((p,i)=><Panel key={p.id} className="plan"><div className="plan-icon"><Dumbbell size={24}/></div><span className="overline">{p.kind==='time'?t('Time-based'):p.kind==='sessions'?t("Session pack"):t("Combined membership")}</span><h2><bdi>{p.name}</bdi></h2><p><bdi>{p.description}</bdi></p><div className="plan-price">{money(p.price,state.settings.currency)}<span> / {t('days',{count:p.days})}</span></div><ul><li><Check size={16}/>{p.gymAccess?t("Unlimited gym access"):t("Class access")}</li>{p.classes&&<li><Check size={16}/>{t('credits',{count:p.credits})}</li>}<li><Check size={16}/>{t('Valid for {{days}}',{days:t('days',{count:p.days})})}</li><li><Check size={16}/>{t("Cash or online payment")}</li></ul><Button variant={i===1?'primary':''} onClick={()=>open('purchase',{planId:p.id})}>{state.user.role==='member'?t("Choose plan"):t("Assign membership")}<ArrowUpRight size={16}/></Button></Panel>)}</div><Panel title={t("Memberships")} className="section-gap"><div className="table-scroll"><table><thead><tr><th>{t("Member")}</th><th>{t("Plan")}</th><th>{t("Status")}</th><th>{t("Valid until")}</th><th>{t("Credits left")}</th></tr></thead><tbody>{state.memberships.map(m=><tr key={m.id}><td><bdi>{state.members.find(x=>x.id===m.memberId)?.name}</bdi></td><td><bdi>{m.planName}</bdi></td><td><Status value={m.status}/></td><td>{date(m.endsAt,{year:'numeric'})}</td><td>{m.classes?number(m.credits):'—'}</td></tr>)}</tbody></table>{!state.memberships.length&&<Empty>{t("Your first membership starts here. Choose a plan above.")}</Empty>}</div></Panel></>;}
export function Schedule({state,open}){const {t}=useTranslation();const [filter,setFilter]=useState('upcoming');const items=state.schedule.filter(c=>filter==='all'||new Date(c.startsAt)>new Date()).sort((a,b)=>new Date(a.startsAt)-new Date(b.startsAt));return <><PageHeading title={t("Make room for movement.")} subtitle={t('Classes and personal training · {{timezone}}',{timezone:state.settings.timezone})}>{['owner','receptionist'].includes(state.user.role)&&<Button variant="primary" onClick={()=>open('class')}><Plus size={17}/>{t("Schedule session")}</Button>}</PageHeading><Panel><div className="list-toolbar"><div className="tabs">{['upcoming','all'].map(f=><button key={f} className={filter===f?'selected':''} onClick={()=>setFilter(f)}>{f==='all'?t("All sessions"):t("Upcoming sessions")}</button>)}</div><span className="quiet">{t('sessions',{count:items.length})}</span></div><div className="schedule-full"><ClassList state={state} items={items} onSelect={c=>open('classDetail',c)}/></div></Panel><Panel title={t("Bookings")} className="section-gap"><div className="table-scroll"><table><thead><tr><th>{t("Session")}</th><th>{t("Member")}</th><th>{t("Date")}</th><th>{t("Status")}</th><th>{t("Action")}</th></tr></thead><tbody>{state.bookings.map(b=>{const c=state.schedule.find(c=>c.id===b.classId);return <tr key={b.id}><td><bdi>{c?.title}</bdi></td><td><bdi>{state.members.find(m=>m.id===b.memberId)?.name}</bdi></td><td>{date(c?.startsAt,{hour:'2-digit',minute:'2-digit',timeZone:state.settings.timezone})}</td><td><Status value={b.status}/></td><td>{b.status==='booked'&&(new Date(c?.startsAt)>new Date()?state.user.role!=='trainer'&&<Button variant="danger-text" onClick={()=>open('cancel',b)}>{t("Cancel booking")}</Button>:state.user.role!=='member'&&<Button onClick={()=>open('markAttendance',b)}>{t("Mark attendance")}</Button>)}</td></tr>;})}</tbody></table>{!state.bookings.length&&<Empty>{t("No bookings yet. Select a session to reserve a spot.")}</Empty>}</div></Panel></>;}
export function Attendance({state,open}){const {t}=useTranslation();
  const member=state.user.role==='member';
  const [search,setSearch]=useState(''),[month,setMonth]=useState('');
  const localDay=value=>new Intl.DateTimeFormat('en-CA',{timeZone:state.settings.timezone,year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date(value));
  const ownRows=state.attendance.filter(a=>!member||a.memberId===state.user.memberId);
  const currentMonth=localDay(new Date()).slice(0,7);
  const rows=ownRows.filter(a=>(!month||localDay(a.createdAt).startsWith(month))&&(member||state.members.find(m=>m.id===a.memberId)?.name.toLowerCase().includes(search.toLowerCase()))).sort((a,b)=>new Date(b.createdAt)-new Date(a.createdAt));
  return <><PageHeading title={member?t("My attendance"):t("Every visit counts.")} subtitle={member?t('Your gym visits, recorded in {{timezone}}',{timezone:state.settings.timezone}):t("Welcome members and keep track of gym attendance.")}>{member?<Button variant="primary" onClick={()=>open('memberQr')}>{t("My QR code")}</Button>:<><Button onClick={()=>open('scanQr')}>{t("Scan QR code")}</Button><Button variant="primary" onClick={()=>open('checkin')}><Plus size={17}/>{t("Check in member")}</Button></>}</PageHeading>
    {member&&<Panel title={t("This month")}><strong className="report-value">{number(ownRows.filter(a=>localDay(a.createdAt).slice(0,7)===currentMonth&&new Date(a.createdAt)<=new Date()).length)}</strong><p>{t('Gym visits in {{month}}',{month:new Date().toLocaleDateString(locale(),{month:'long',year:'numeric',timeZone:state.settings.timezone})})}</p></Panel>}
    <Panel className={member?'section-gap':''}><div className="list-toolbar"><h2>{t("Visit history")}</h2>{!member&&<SearchBox value={search} onChange={setSearch}/>}</div><div className="report-filters"><Field label={t("Filter by month")}><input type="month" value={month} onChange={e=>setMonth(e.target.value)}/></Field>{month&&<Button onClick={()=>setMonth('')}>{t("All months")}</Button>}</div><div className="table-scroll"><table><thead><tr>{!member&&<th>{t("Member")}</th>}<th>{t("Date")}</th><th>{t("Time")}</th><th>{t("Status")}</th></tr></thead><tbody>{rows.map(a=>{const m=state.members.find(m=>m.id===a.memberId);return <tr key={a.id}>{!member&&<td><span className="person"><Avatar name={m?.name} photo={m?.photo}/><bdi>{m?.name}</bdi></span></td>}<td>{date(a.createdAt,{year:'numeric',timeZone:state.settings.timezone})}</td><td>{date(a.createdAt,{month:undefined,day:undefined,hour:'2-digit',minute:'2-digit',timeZone:state.settings.timezone})}</td><td><Status value="checked in"/></td></tr>;})}</tbody></table>{!rows.length&&<Empty>{t("No visits found for this period.")}</Empty>}</div></Panel></>;
}
export function Team({state,open}){const {t}=useTranslation();return <><PageHeading title={t("Your team. Your strength.")} subtitle={t("The people who keep your gym moving.")}><Button variant="primary" onClick={()=>open('staff')}><Plus size={17}/>{t("Add team member")}</Button></PageHeading><Panel><div className="table-scroll"><table><thead><tr><th>{t("Team member")}</th><th>{t("Email")}</th><th>{t("Role")}</th><th>{t("Access")}</th></tr></thead><tbody>{state.users.map(u=><tr key={u.id}><td><span className="person"><Avatar name={u.name}/><strong><bdi>{u.name}</bdi></strong></span></td><td><bdi>{u.email}</bdi></td><td className="capitalize">{t(u.role)}</td><td>{u.role==='owner'?t("Full gym access"):u.role==='trainer'?t("Assigned sessions and participants"):t("Members, payments and attendance")}</td></tr>)}</tbody></table></div></Panel></>;}
export function Settings({state,act}){const {t}=useTranslation();const [busy,setBusy]=useState(false);return <><PageHeading title={t("Make Forma yours.")} subtitle={t("The details that make your gym run smoothly.")}/><Panel title={t("Gym details")} className="settings-panel"><form onSubmit={async e=>{e.preventDefault();const f=Object.fromEntries(new FormData(e.currentTarget));f.cancellationHours=Number(f.cancellationHours);setBusy(true);await act('/settings',f,"Gym settings saved.",null,'PATCH');setBusy(false);}}><div className="form-grid"><Field label={t("Gym name")}><input dir="auto" name="name" required defaultValue={state.settings.name}/></Field><Field label={t("Contact email")}><input name="email" type="email" required defaultValue={state.settings.email}/></Field><Field label={t("Currency")}><select name="currency" defaultValue={state.settings.currency}>{['USD','EUR','GBP','MAD','CAD','AUD'].map(c=><option key={c}>{c}</option>)}</select></Field><Field label={t("Timezone")}><input dir="auto" name="timezone" required defaultValue={state.settings.timezone} list="timezones"/><datalist id="timezones">{['Africa/Casablanca','Europe/London','Europe/Paris','America/New_York','Asia/Dubai','Asia/Tokyo','Australia/Sydney'].map(t=><option key={t} value={t}/>)}</datalist></Field><Field label={t("Free cancellation deadline (hours)")}><input name="cancellationHours" type="number" min="0" max="72" required defaultValue={state.settings.cancellationHours}/></Field></div><p className="form-note">{t("Cancellations before this deadline return the session credit. Currency is locked once payments exist.")}</p><div className="form-actions"><Button variant="primary" disabled={busy}>{busy?t("Saving…"):t("Save changes")}</Button></div></form></Panel></>;}
export function MemberHome({state,open,navigate}){const {t}=useTranslation();const m=state.memberships.find(m=>m.status==='active');const now=new Date();const month=value=>new Intl.DateTimeFormat('en-CA',{timeZone:state.settings.timezone,year:'numeric',month:'2-digit'}).format(new Date(value));const monthlyVisits=state.attendance.filter(a=>a.memberId===state.user.memberId&&new Date(a.createdAt)<=now&&month(a.createdAt)===month(now)).length;return <><PageHeading title={t('Good to see you, {{name}}.',{name:state.user.name.split(' ')[0]})} subtitle={t("A stronger you starts with showing up.")}><Button variant="primary" onClick={()=>open('memberQr')}>{t("Check in")}</Button><Button onClick={()=>navigate('schedule')}><CalendarDays size={17}/>{t("Book a session")}</Button></PageHeading><Panel title={t("Attendance this month")} className="overview-attendance" action={<Button onClick={()=>navigate('attendance')}>{t("View history")}</Button>}><strong className="report-value">{number(monthlyVisits)}</strong><p>{t('Gym visits in {{month}}',{month:now.toLocaleDateString(locale(),{month:'long',year:'numeric',timeZone:state.settings.timezone})})}</p></Panel><div className="member-home-grid"><Panel title={t("Your membership")}><div className="membership-card"><Dumbbell size={35}/><span>{state.settings.name}</span><h2>{m?.planName||t("Your next chapter starts here")}</h2><div>{m?<><Status value={m.status}/><p>{t('Valid until {{date}}',{date:date(m.endsAt,{year:'numeric'})})}</p><strong>{m.classes?t('Available: {{credits}}',{credits:t('credits',{count:m.credits})}):t("Unlimited gym access")}</strong></>:<p>{t("Choose a membership and start moving.")}</p>}</div></div><Button className="full-width" onClick={()=>navigate('memberships')}>{m?t("Explore plans & renew"):t("Choose a plan")}<ArrowUpRight size={16}/></Button></Panel><Panel title={t("Your next sessions")}><ClassList state={state} items={state.schedule.filter(c=>state.bookings.some(b=>b.classId===c.id&&b.status==='booked')).sort((a,b)=>new Date(a.startsAt)-new Date(b.startsAt))} onSelect={c=>open('classDetail',c)}/></Panel></div><Panel title={t("Discover a session")} className="section-gap"><ClassList state={state} items={state.schedule.filter(c=>new Date(c.startsAt)>new Date()).slice(0,3)} onSelect={c=>open('classDetail',c)}/></Panel></>;}
