import {useState} from 'react';
import {Plus,Download,Check,ArrowUpRight,CalendarDays,Dumbbell,Clock,Mail,ShieldCheck} from 'lucide-react';
import {Button,Panel,Status,SearchBox,Empty,Avatar,Field} from '../components/ui';
import {money,date,latestMembership} from '../api';
import {MemberRows,ClassList} from './Dashboard';
export function PageHeading({title,subtitle,children}){return <div className="page-heading"><div><h1>{title}</h1><p>{subtitle}</p></div><div className="heading-actions">{children}</div></div>;}
export function Members({state,open}){
  const [search,setSearch]=useState(''),[filter,setFilter]=useState('all');const rows=state.members.filter(m=>(m.name+' '+m.email).toLowerCase().includes(search.toLowerCase())&&(filter==='all'||latestMembership(state,m.id)?.status===filter));
  return <><PageHeading title="Your members." subtitle="The people at the heart of your gym."><Button variant="primary" onClick={()=>open('member')}><Plus size={17}/>Add member</Button></PageHeading><Panel><div className="list-toolbar"><div className="tabs">{['all','active','pending','expired'].map(f=><button key={f} onClick={()=>setFilter(f)} className={filter===f?'selected':''}>{f==='all'?'All members':f}</button>)}</div><SearchBox value={search} onChange={setSearch}/></div><MemberRows state={state} rows={rows} onSelect={m=>open('memberDetail',m)}/><div className="table-footer">{rows.length} members</div></Panel></>;
}
export function Memberships({state,open}){return <><PageHeading title={state.user.role==='member'?'Find your next step.':'Plans that fit your members.'} subtitle="Gym access, class packs, and everything in between.">{state.user.role==='owner'&&<Button variant="primary" onClick={()=>open('plan')}><Plus size={17}/>Create plan</Button>}</PageHeading><div className="plan-grid">{state.plans.map((p,i)=><Panel key={p.id} className="plan"><div className="plan-icon"><Dumbbell size={24}/></div><span className="overline">{p.kind==='time'?'Time-based':p.kind==='sessions'?'Session pack':'Combined membership'}</span><h2>{p.name}</h2><p>{p.description}</p><div className="plan-price">{money(p.price,state.settings.currency)}<span> / {p.days} days</span></div><ul><li><Check size={16}/>{p.gymAccess?'Unlimited gym access':'Class access'}</li>{p.classes&&<li><Check size={16}/>{p.credits} session credits</li>}<li><Check size={16}/>{p.days} days of validity</li><li><Check size={16}/>Cash or online payment</li></ul><Button variant={i===1?'primary':''} onClick={()=>open('purchase',{planId:p.id})}>{state.user.role==='member'?'Choose plan':'Assign membership'}<ArrowUpRight size={16}/></Button></Panel>)}</div><Panel title="Memberships" className="section-gap"><div className="table-scroll"><table><thead><tr><th>Member</th><th>Plan</th><th>Status</th><th>Valid until</th><th>Credits left</th></tr></thead><tbody>{state.memberships.map(m=><tr key={m.id}><td>{state.members.find(x=>x.id===m.memberId)?.name}</td><td>{m.planName}</td><td><Status value={m.status}/></td><td>{date(m.endsAt,{year:'numeric'})}</td><td>{m.classes?m.credits:'—'}</td></tr>)}</tbody></table>{!state.memberships.length&&<Empty>Your first membership starts here. Choose a plan above.</Empty>}</div></Panel></>;}
export function Schedule({state,open}){const [filter,setFilter]=useState('upcoming');const items=state.schedule.filter(c=>filter==='all'||new Date(c.startsAt)>new Date()).sort((a,b)=>new Date(a.startsAt)-new Date(b.startsAt));return <><PageHeading title="Make room for movement." subtitle={'Classes and personal training · '+state.settings.timezone}>{['owner','receptionist'].includes(state.user.role)&&<Button variant="primary" onClick={()=>open('class')}><Plus size={17}/>Schedule session</Button>}</PageHeading><Panel><div className="list-toolbar"><div className="tabs">{['upcoming','all'].map(f=><button key={f} className={filter===f?'selected':''} onClick={()=>setFilter(f)}>{f==='all'?'All sessions':'Upcoming sessions'}</button>)}</div><span className="quiet">{items.length} sessions</span></div><div className="schedule-full"><ClassList state={state} items={items} onSelect={c=>open('classDetail',c)}/></div></Panel><Panel title="Bookings" className="section-gap"><div className="table-scroll"><table><thead><tr><th>Session</th><th>Member</th><th>Date</th><th>Status</th><th>Action</th></tr></thead><tbody>{state.bookings.map(b=>{const c=state.schedule.find(c=>c.id===b.classId);return <tr key={b.id}><td>{c?.title}</td><td>{state.members.find(m=>m.id===b.memberId)?.name}</td><td>{date(c?.startsAt,{hour:'2-digit',minute:'2-digit',timeZone:state.settings.timezone})}</td><td><Status value={b.status}/></td><td>{b.status==='booked'&&(new Date(c?.startsAt)>new Date()?state.user.role!=='trainer'&&<Button variant="danger-text" onClick={()=>open('cancel',b)}>Cancel booking</Button>:state.user.role!=='member'&&<Button onClick={()=>open('markAttendance',b)}>Mark attendance</Button>)}</td></tr>;})}</tbody></table>{!state.bookings.length&&<Empty>No bookings yet. Select a session to reserve a spot.</Empty>}</div></Panel></>;}
export function Attendance({state,open}){
  const member=state.user.role==='member';
  const [search,setSearch]=useState(''),[month,setMonth]=useState('');
  const localDay=value=>new Intl.DateTimeFormat('en-CA',{timeZone:state.settings.timezone,year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date(value));
  const ownRows=state.attendance.filter(a=>!member||a.memberId===state.user.memberId);
  const currentMonth=localDay(new Date()).slice(0,7);
  const rows=ownRows.filter(a=>(!month||localDay(a.createdAt).startsWith(month))&&(member||state.members.find(m=>m.id===a.memberId)?.name.toLowerCase().includes(search.toLowerCase()))).sort((a,b)=>new Date(b.createdAt)-new Date(a.createdAt));
  return <><PageHeading title={member?'My attendance':'Every visit counts.'} subtitle={member?'Your gym visits, recorded in '+state.settings.timezone:'Welcome members and keep track of gym attendance.'}>{member?<Button variant="primary" onClick={()=>open('memberQr')}>My QR code</Button>:<><Button onClick={()=>open('scanQr')}>Scan QR code</Button><Button variant="primary" onClick={()=>open('checkin')}><Plus size={17}/>Check in member</Button></>}</PageHeading>
    {member&&<Panel title="This month"><strong className="report-value">{ownRows.filter(a=>localDay(a.createdAt).slice(0,7)===currentMonth&&new Date(a.createdAt)<=new Date()).length}</strong><p>Recorded gym visits in {currentMonth}</p></Panel>}
    <Panel className={member?'section-gap':''}><div className="list-toolbar"><h2>Visit history</h2>{!member&&<SearchBox value={search} onChange={setSearch}/>}</div><div className="report-filters"><Field label="Filter by month"><input type="month" value={month} onChange={e=>setMonth(e.target.value)}/></Field>{month&&<Button onClick={()=>setMonth('')}>All months</Button>}</div><div className="table-scroll"><table><thead><tr>{!member&&<th>Member</th>}<th>Date</th><th>Time</th><th>Status</th></tr></thead><tbody>{rows.map(a=>{const m=state.members.find(m=>m.id===a.memberId);return <tr key={a.id}>{!member&&<td><span className="person"><Avatar name={m?.name} photo={m?.photo}/>{m?.name}</span></td>}<td>{date(a.createdAt,{year:'numeric',timeZone:state.settings.timezone})}</td><td>{date(a.createdAt,{month:undefined,day:undefined,hour:'2-digit',minute:'2-digit',timeZone:state.settings.timezone})}</td><td><Status value="checked in"/></td></tr>;})}</tbody></table>{!rows.length&&<Empty>No visits found for this period.</Empty>}</div></Panel></>;
}
export function Team({state,open}){return <><PageHeading title="Your team. Your strength." subtitle="The people who keep your gym moving."><Button variant="primary" onClick={()=>open('staff')}><Plus size={17}/>Add team member</Button></PageHeading><Panel><div className="table-scroll"><table><thead><tr><th>Team member</th><th>Email</th><th>Role</th><th>Access</th></tr></thead><tbody>{state.users.map(u=><tr key={u.id}><td><span className="person"><Avatar name={u.name}/><strong>{u.name}</strong></span></td><td>{u.email}</td><td className="capitalize">{u.role}</td><td>{u.role==='owner'?'Full gym access':u.role==='trainer'?'Assigned sessions and participants':'Members, payments and attendance'}</td></tr>)}</tbody></table></div></Panel></>;}
export function Settings({state,act}){const [busy,setBusy]=useState(false);return <><PageHeading title="Make Forma yours." subtitle="The details that make your gym run smoothly."/><Panel title="Gym details" className="settings-panel"><form onSubmit={async e=>{e.preventDefault();const f=Object.fromEntries(new FormData(e.currentTarget));f.cancellationHours=Number(f.cancellationHours);setBusy(true);await act('/settings',f,'Gym settings saved.',null,'PATCH');setBusy(false);}}><div className="form-grid"><Field label="Gym name"><input name="name" required defaultValue={state.settings.name}/></Field><Field label="Contact email"><input name="email" type="email" required defaultValue={state.settings.email}/></Field><Field label="Currency"><select name="currency" defaultValue={state.settings.currency}>{['USD','EUR','GBP','MAD','CAD','AUD'].map(c=><option key={c}>{c}</option>)}</select></Field><Field label="Timezone"><input name="timezone" required defaultValue={state.settings.timezone} list="timezones"/><datalist id="timezones">{['Africa/Casablanca','Europe/London','Europe/Paris','America/New_York','Asia/Dubai','Asia/Tokyo','Australia/Sydney'].map(t=><option key={t} value={t}/>)}</datalist></Field><Field label="Free cancellation deadline (hours)"><input name="cancellationHours" type="number" min="0" max="72" required defaultValue={state.settings.cancellationHours}/></Field></div><p className="form-note">Cancellations before this deadline return the session credit. Currency is locked once payments exist.</p><div className="form-actions"><Button variant="primary" disabled={busy}>{busy?'Saving…':'Save changes'}</Button></div></form></Panel></>;}
export function MemberHome({state,open,navigate}){const m=state.memberships.find(m=>m.status==='active');const now=new Date();const month=value=>new Intl.DateTimeFormat('en-CA',{timeZone:state.settings.timezone,year:'numeric',month:'2-digit'}).format(new Date(value));const monthlyVisits=state.attendance.filter(a=>a.memberId===state.user.memberId&&new Date(a.createdAt)<=now&&month(a.createdAt)===month(now)).length;return <><PageHeading title={'Good to see you, '+state.user.name.split(' ')[0]+'.'} subtitle="A stronger you starts with showing up."><Button variant="primary" onClick={()=>open('memberQr')}>Check in</Button><Button onClick={()=>navigate('schedule')}><CalendarDays size={17}/>Book a session</Button></PageHeading><Panel title="Attendance this month" className="overview-attendance" action={<Button onClick={()=>navigate('attendance')}>View history</Button>}><strong className="report-value">{monthlyVisits}</strong><p>Gym visits in {now.toLocaleDateString(undefined,{month:'long',year:'numeric',timeZone:state.settings.timezone})}</p></Panel><div className="member-home-grid"><Panel title="Your membership"><div className="membership-card"><Dumbbell size={35}/><span>{state.settings.name}</span><h2>{m?.planName||'Your next chapter starts here'}</h2><div>{m?<><Status value={m.status}/><p>Valid until {date(m.endsAt,{year:'numeric'})}</p><strong>{m.classes?m.credits+' session credits available':'Unlimited gym access'}</strong></>:<p>Choose a membership and start moving.</p>}</div></div><Button className="full-width" onClick={()=>navigate('memberships')}>{m?'Explore plans & renew':'Choose a plan'}<ArrowUpRight size={16}/></Button></Panel><Panel title="Your next sessions"><ClassList state={state} items={state.schedule.filter(c=>state.bookings.some(b=>b.classId===c.id&&b.status==='booked')).sort((a,b)=>new Date(a.startsAt)-new Date(b.startsAt))} onSelect={c=>open('classDetail',c)}/></Panel></div><Panel title="Discover a session" className="section-gap"><ClassList state={state} items={state.schedule.filter(c=>new Date(c.startsAt)>new Date()).slice(0,3)} onSelect={c=>open('classDetail',c)}/></Panel></>;}
