
import {useTranslation} from 'react-i18next';
import LanguageSwitcher from '../components/LanguageSwitcher';
import {useState} from 'react';
import {api} from '../api';
import {Button,Field,Panel} from '../components/ui';
export default function PasswordReset({token,onReset}){const {t}=useTranslation();
  const [busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState('');
  async function submit(event){event.preventDefault();const values=new FormData(event.currentTarget);if(token&&values.get('password')!==values.get('confirm')){setError("Passwords must match.");return;}setBusy(true);setError('');try{const result=await api(token?'/auth/reset-password':'/auth/forgot-password',token?{token,password:values.get('password')}:{email:values.get('email')});if(token){onReset();setMessage("Your password has been reset. Sign in with your new password.");}else setMessage(result.message);}catch(e){setError(e.message);}finally{setBusy(false);}}
  return <main className="invitation-accept"><LanguageSwitcher className="recovery-language"/><Panel title={token?t("Choose a new password"):t("Reset your password")}><p>{token?t("Use at least 10 characters. Resetting your password signs out your existing sessions."):t("Enter your account email to receive a reset link.")}</p>{error&&<p className="form-error" role="alert">{t(error)}</p>}{message?<p role="status" className="qr-success">{t(message)}</p>:<form onSubmit={submit}>{token?<><Field label={t("New password")}><input dir="auto" name="password" type="password" required minLength={10} maxLength={128} autoComplete="new-password"/></Field><Field label={t("Confirm password")}><input dir="auto" name="confirm" type="password" required minLength={10} maxLength={128} autoComplete="new-password"/></Field></>:<Field label={t("Email address")}><input name="email" type="email" required maxLength={254} autoComplete="email"/></Field>}<Button variant="primary" disabled={busy}>{busy?t("Please wait…"):token?t("Save new password"):t("Send reset link")}</Button></form>}<p className="quiet">{t("Links expire after 30 minutes. If no email arrives, check spam or contact reception.")}</p><a href="#overview">{t("Back to sign in")}</a>{token&&<p><a href="#forgot-password">{t("Request a new reset link")}</a></p>}</Panel></main>;
}
