import {locale,number} from "../i18n";
import {useTranslation} from 'react-i18next';
import {useEffect,useState} from 'react';
import {api,money} from '../api';
import {Panel,Button,Field,Empty} from '../components/ui';
export default function Reports({state}){const {t}=useTranslation();
  const today=new Intl.DateTimeFormat('en-CA',{timeZone:state.settings.timezone,year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
  const [range,setRange]=useState({from:today.slice(0,8)+'01',to:today}),[data,setData]=useState(null),[error,setError]=useState(''),[loading,setLoading]=useState(true);
  useEffect(()=>{let current=true;setLoading(true);setError('');api('/reports?'+new URLSearchParams(range)).then(value=>{if(current)setData(value);}).catch(e=>{if(current)setError(e.message);}).finally(()=>{if(current)setLoading(false);});return()=>{current=false;};},[range]);
  return <><div className="page-heading"><div><h1>{t("Revenue & retention")}</h1><p>{t('Confirmed payments and membership activity in {{timezone}}.',{timezone:state.settings.timezone})}</p></div></div><Panel><form className="report-filters" onSubmit={e=>{e.preventDefault();setRange(Object.fromEntries(new FormData(e.currentTarget)));}}><Field label={t("From")}><input name="from" type="date" required defaultValue={range.from} max={today}/></Field><Field label={t("Through")}><input name="to" type="date" required defaultValue={range.to} max={today}/></Field><Button variant="primary" disabled={loading}>{t("Apply dates")}</Button></form></Panel>
    {error&&<p className="form-error" role="alert">{t(error)}</p>}{loading?<Empty>{t("Loading report…")}</Empty>:!error&&data&&<>
      <div className="report-summary section-gap">{[[t("Members at start"),data.openingMembers],[t("Members at end"),data.closingMembers],[t("Retained members"),data.retained],[t("Retention"),data.retentionRate===null?t("No starting cohort"):number(data.retentionRate/100,{style:'percent',maximumFractionDigits:1})],[t("New members"),data.newMembers],[t("Gym visits"),data.visits]].map(([title,value])=><Panel key={title} title={title}><strong className="report-value">{typeof value==='number'?number(value):value}</strong></Panel>)}</div>
      <Panel title={t("Collected revenue")} className="section-gap"><p>{t("Paid payments by payment date. Pending and failed payments are excluded. This is gross collected revenue, before processing fees.")}</p><div className="table-scroll"><table><thead><tr><th>{t("Currency")}</th><th>{t("Cash")}</th><th>{t("Online")}</th><th>{t("Total")}</th><th>{t("Payments")}</th></tr></thead><tbody>{data.revenue.map(row=><tr key={row.currency}><td>{row.currency}</td><td>{money(row.cash,row.currency)}</td><td>{money(row.online,row.currency)}</td><td><strong>{money(row.total,row.currency)}</strong></td><td>{number(row.count)}</td></tr>)}</tbody></table>{!data.revenue.length&&<Empty>{t("No completed payments in this period.")}</Empty>}</div></Panel>
      <Panel title={t("Monthly revenue")} className="section-gap"><div className="table-scroll"><table><thead><tr><th>{t("Month")}</th><th>{t("Currency")}</th><th>{t("Collected")}</th></tr></thead><tbody>{data.monthly.map(row=><tr key={row.month+row.currency}><td>{new Date(row.month+'-01T12:00:00Z').toLocaleDateString(locale(),{month:'long',year:'numeric',timeZone:'UTC'})}</td><td>{row.currency}</td><td>{money(row.total,row.currency)}</td></tr>)}</tbody></table>{!data.monthly.length&&<Empty>{t("No revenue to display.")}</Empty>}</div></Panel>
      <Panel title={t("Retention & renewals")} className="section-gap"><p>{t('{{count}} of the members active at the start no longer have an active paid membership at the end.',{count:data.lost})}</p><p>{t('{{renewed}} / {{eligible}} members with a membership ending in this period started a replacement membership by the end of the period.',{renewed:number(data.renewed),eligible:number(data.renewalEligible)})}</p><p className="quiet">{t("Retention compares the same opening cohort at both boundaries; new joiners are excluded. Any paid membership counts as active, including class packs. Renewals are measured per member across plans. Current-day reports run up to now. Future renewals are excluded until they start.")}</p><p className="quiet">{t("These figures use recorded membership validity dates. Historical cancellation and refund adjustments are not yet supported.")}</p></Panel>
    </>}</>;
}
