import {useEffect,useState} from 'react';
import {api,money} from '../api';
import {Panel,Button,Field,Empty} from '../components/ui';
export default function Reports({state}){
  const today=new Intl.DateTimeFormat('en-CA',{timeZone:state.settings.timezone,year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
  const [range,setRange]=useState({from:today.slice(0,8)+'01',to:today}),[data,setData]=useState(null),[error,setError]=useState(''),[loading,setLoading]=useState(true);
  useEffect(()=>{let current=true;setLoading(true);setError('');api('/reports?'+new URLSearchParams(range)).then(value=>{if(current)setData(value);}).catch(e=>{if(current)setError(e.message);}).finally(()=>{if(current)setLoading(false);});return()=>{current=false;};},[range]);
  return <><div className="page-heading"><div><h1>Revenue & retention</h1><p>Confirmed payments and membership activity in {state.settings.timezone}.</p></div></div><Panel><form className="report-filters" onSubmit={e=>{e.preventDefault();setRange(Object.fromEntries(new FormData(e.currentTarget)));}}><Field label="From"><input name="from" type="date" required defaultValue={range.from} max={today}/></Field><Field label="Through"><input name="to" type="date" required defaultValue={range.to} max={today}/></Field><Button variant="primary" disabled={loading}>Apply dates</Button></form></Panel>
    {error&&<p className="form-error" role="alert">{error}</p>}{loading?<Empty>Loading report…</Empty>:!error&&data&&<>
      <div className="report-summary section-gap">{[['Members at start',data.openingMembers],['Members at end',data.closingMembers],['Retained members',data.retained],['Retention',data.retentionRate===null?'No starting cohort':data.retentionRate+'%'],['New members',data.newMembers],['Gym visits',data.visits]].map(([title,value])=><Panel key={title} title={title}><strong className="report-value">{value}</strong></Panel>)}</div>
      <Panel title="Collected revenue" className="section-gap"><p>Paid payments by payment date. Pending and failed payments are excluded. This is gross collected revenue, before processing fees.</p><div className="table-scroll"><table><thead><tr><th>Currency</th><th>Cash</th><th>Online</th><th>Total</th><th>Payments</th></tr></thead><tbody>{data.revenue.map(row=><tr key={row.currency}><td>{row.currency}</td><td>{money(row.cash,row.currency)}</td><td>{money(row.online,row.currency)}</td><td><strong>{money(row.total,row.currency)}</strong></td><td>{row.count}</td></tr>)}</tbody></table>{!data.revenue.length&&<Empty>No completed payments in this period.</Empty>}</div></Panel>
      <Panel title="Monthly revenue" className="section-gap"><div className="table-scroll"><table><thead><tr><th>Month</th><th>Currency</th><th>Collected</th></tr></thead><tbody>{data.monthly.map(row=><tr key={row.month+row.currency}><td>{row.month}</td><td>{row.currency}</td><td>{money(row.total,row.currency)}</td></tr>)}</tbody></table>{!data.monthly.length&&<Empty>No revenue to display.</Empty>}</div></Panel>
      <Panel title="Retention & renewals" className="section-gap"><p><strong>{data.lost}</strong> of the members active at the start no longer have an active paid membership at the end.</p><p><strong>{data.renewed} / {data.renewalEligible}</strong> members with a membership ending in this period started a replacement membership by the end of the period.</p><p className="quiet">Retention compares the same opening cohort at both boundaries; new joiners are excluded. Any paid membership counts as active, including class packs. Renewals are measured per member across plans. Current-day reports run up to now. Future renewals are excluded until they start.</p><p className="quiet">These figures use recorded membership validity dates. Historical cancellation and refund adjustments are not yet supported.</p></Panel>
    </>}</>;
}
