import {number} from "../i18n";
import {useTranslation} from 'react-i18next';
import {useState} from 'react';
import {Button,Modal,Field,Status,Avatar,Empty} from './ui';
import {api,money,date} from '../api';
import {goToCheckout} from '../checkout';
export default function Dialogs({dialog,state,close,act,open}){const {t}=useTranslation();
  const {type,data={}}=dialog;const [busy,setBusy]=useState(false);const [error,setError]=useState('');
  const titles={member:t("Add a member"),memberDetail:t("Member profile"),plan:t("Create a membership plan"),purchase:t("Start a membership"),class:t("Schedule a session"),classDetail:t("Session details"),checkin:t("Check in a member"),staff:t("Add a team member"),receipt:t("Payment receipt"),confirmPayment:t("Confirm cash payment"),cancel:t("Cancel booking"),markAttendance:t("Record attendance")};
  const memberSelect=(defaultValue=data.memberId)=><select name="memberId" required defaultValue={defaultValue||state.user.memberId||''}><option value="" disabled>{t("Select a member")}</option>{state.members.map(m=><option value={m.id} key={m.id}><bdi>{m.name}</bdi></option>)}</select>;
  async function submit(e){e.preventDefault();setError('');setBusy(true);const f=Object.fromEntries(new FormData(e.currentTarget));let path,body=f;
    if(type==='member')path='/members';
    if(type==='staff')path='/team';
    if(type==='plan'){path='/plans';body={...f,price:Math.round(Number(f.price)*100),days:Number(f.days),credits:Number(f.credits),gymAccess:f.gymAccess==='on',classes:f.classes==='on'};}
    if(type==='purchase'){path='/purchases';if(state.user.role==='member')body.memberId=state.user.memberId;}
    if(type==='class'){path='/schedule';body={...f,startsAt:new Date(f.startsAt).toISOString(),capacity:Number(f.capacity),duration:Number(f.duration)};}
    if(type==='classDetail'){path='/bookings';body={memberId:state.user.role==='member'?state.user.memberId:f.memberId,classId:data.id};}
    if(type==='checkin')path='/attendance';
    if(type==='confirmPayment'){path='/payments/'+data.id+'/confirm';body={};}
    if(type==='cancel'){path='/bookings/'+data.id+'/cancel';body={};}
    if(type==='markAttendance')path='/bookings/'+data.id+'/attendance';
    const result=await act(path,body,type==='purchase'?"Purchase created. Payment confirmation activates the membership.":"Changes saved.",null,'POST',true);
    if(result.error)setError(result.error);
    else if(type==='purchase'&&body.method==='online'){
      try{
        const checkout=await api('/payments/'+result.id+'/checkout',{});
        if(!goToCheckout(checkout))close();
      }catch(e){setError(t('{{error}} Your purchase is saved. You can retry here or from Payments.',{error:e.message}));}
    }else close();setBusy(false);
  }
  const actions=<div className="form-actions"><Button type="button" onClick={close}>{t("Cancel")}</Button><Button variant={type==='cancel'?'danger':'primary'} disabled={busy}>{busy?t("Saving…"):({member:t("Add member"),staff:t("Create account"),plan:t("Create plan"),purchase:t("Create purchase"),class:t("Schedule session"),classDetail:t("Book session"),checkin:t("Check in"),confirmPayment:t("Confirm payment received"),cancel:t("Cancel booking"),markAttendance:t("Save attendance")})[type]}</Button></div>;
  if(type==='receipt')return <Modal title={titles[type]} onClose={close}><div className="receipt"><strong className="receipt-brand">FORMA.</strong><p>{state.settings.name}</p><Status value="paid"/><h2>{money(data.amount,data.currency)}</h2><dl><dt>{t("Member")}</dt><dd><bdi>{state.members.find(m=>m.id===data.memberId)?.name}</bdi></dd><dt>{t("Membership")}</dt><dd><bdi>{data.description}</bdi></dd><dt>{t("Payment method")}</dt><dd>{t(data.method)}</dd><dt>{t("Paid on")}</dt><dd>{date(data.paidAt,{year:'numeric'})}</dd><dt>{t("Reference")}</dt><dd className="reference">{data.id}</dd></dl><p className="form-note">{t("Payment acknowledgement. This is not a tax invoice.")}</p></div><div className="form-actions"><Button onClick={close}>{t("Close")}</Button><Button variant="primary" onClick={()=>window.print()}>{t("Print receipt")}</Button></div></Modal>;
  if(type==='memberDetail'){const memberships=state.memberships.filter(m=>m.memberId===data.id);return <Modal title={titles[type]} onClose={close}><div className="profile-detail"><Avatar name={data.name}/><h3><bdi>{data.name}</bdi></h3><p><bdi>{data.email}</bdi></p><p>{data.phone?<bdi dir="ltr">{data.phone}</bdi>:t("No phone number")}</p></div><h3>{t("Membership history")}</h3>{memberships.map(m=><div className="detail-row" key={m.id}><div><strong><bdi>{m.planName}</bdi></strong><small>{date(m.startsAt)} – {date(m.endsAt)}{m.classes?' · '+t('credits',{count:m.credits}):''}</small></div><Status value={m.status}/></div>)}{!memberships.length&&<Empty>{t("No membership yet.")}</Empty>}<div className="form-actions"><Button onClick={()=>open('checkin',{memberId:data.id})}>{t("Check in")}</Button><Button variant="primary" onClick={()=>open('purchase',{memberId:data.id})}>{t("Assign / renew plan")}</Button></div></Modal>;}
  const booked=type==='classDetail'&&state.bookings.some(b=>b.classId===data.id&&b.memberId===state.user.memberId&&b.status!=='cancelled');
  return <Modal title={titles[type]} onClose={close}><form onSubmit={submit}>{error&&<div className="form-error" role="alert">{t(error)}</div>}
    {['member','staff'].includes(type)&&<><div className="form-grid"><Field label={t("Full name")}><input dir="auto" autoFocus name="name" required maxLength="120" placeholder={t("e.g. Jordan Taylor")}/></Field><Field label={t("Email address")}><input name="email" type="email" required placeholder="jordan@example.com"/></Field><Field label={t("Phone number (optional)")}><input name="phone" type="tel" maxLength="40" placeholder="+1 555 010 1234"/></Field>{type==='staff'&&<><Field label={t("Role")}><select name="role"><option value="trainer">{t("Trainer")}</option><option value="receptionist">{t("Receptionist")}</option></select></Field><Field label={t("Initial password")}><input dir="auto" name="password" type="password" required minLength="10" maxLength="128" autoComplete="new-password"/></Field></>}</div>{type==='member'&&<p className="form-note">{t("Create the profile first, then assign a membership from the member’s profile.")}</p>}</>}
    {type==='plan'&&<div className="form-grid"><Field label={t("Plan name")}><input dir="auto" name="name" required maxLength="120"/></Field><Field label={t("Type")}><select name="kind"><option value="time">{t("Time-based")}</option><option value="sessions">{t("Session pack")}</option><option value="combined">{t("Combined")}</option></select></Field><Field label={t('Price ({{currency}})',{currency:state.settings.currency})}><input name="price" type="number" step="0.01" min="1" required/></Field><Field label={t("Validity (days)")}><input name="days" type="number" min="1" max="730" defaultValue="30" required/></Field><Field label={t("Session credits")}><input name="credits" type="number" min="0" max="1000" defaultValue="0" required/></Field><Field label={t("Description")}><input dir="auto" name="description" maxLength="250" required/></Field><label className="checkbox"><input name="gymAccess" type="checkbox" defaultChecked/>{t("Includes gym access")}</label><label className="checkbox"><input name="classes" type="checkbox"/>{t("Includes class bookings")}</label></div>}
    {type==='purchase'&&<><div className="form-grid">{state.user.role!=='member'&&<Field label={t("Member")}>{memberSelect()}</Field>}<Field label={t("Membership plan")}><select name="planId" required defaultValue={data.planId||''}><option value="" disabled>{t("Select a plan")}</option>{state.plans.map(p=><option value={p.id} key={p.id}><bdi>{p.name}</bdi> · {money(p.price,state.settings.currency)}</option>)}</select></Field><Field label={t("Payment method")}><select name="method"><option value="cash">{t("Cash at reception")}</option><option value="online" disabled={!state.onlineEnabled}>{t("Online payment")}{!state.onlineEnabled?t(' (not connected)'):''}</option></select></Field></div><p className="form-note">{t("Membership starts once payment is confirmed. Cash payments are confirmed by staff from Payments. Online purchases open secure Stripe Checkout. If interrupted, you can resume from Payments.")}</p></>}
    {type==='class'&&<div className="form-grid"><Field label={t("Session title")}><input dir="auto" name="title" required maxLength="120"/></Field><Field label={t("Session type")}><select name="type"><option value="Group class">{t("Group class")}</option><option value="Personal training">{t("Personal training")}</option></select></Field><Field label={t("Trainer")}><select name="trainerId" required><option value="">{t("Choose a trainer")}</option>{state.users.filter(u=>u.role==='trainer').map(u=><option key={u.id} value={u.id}><bdi>{u.name}</bdi></option>)}</select></Field><Field label={t("Date & time (your device timezone)")}><input name="startsAt" type="datetime-local" required/></Field><Field label={t("Duration (minutes)")}><input name="duration" type="number" min="15" max="240" defaultValue="50" required/></Field><Field label={t("Capacity (personal training uses 1)")}><input name="capacity" type="number" min="1" max="200" defaultValue="12" required/></Field><Field label={t("Room")}><input dir="auto" name="room" required defaultValue="Studio A"/></Field></div>}
    {type==='classDetail'&&<><h3><bdi>{data.title}</bdi></h3><div className="session-details"><span>{date(data.startsAt,{weekday:'short',hour:'2-digit',minute:'2-digit',timeZone:state.settings.timezone})}</span><span>{t('{{minutes}} minutes · {{room}}',{minutes:number(data.duration),room:data.room})}</span><span><bdi>{state.users.find(u=>u.id===data.trainerId)?.name}</bdi></span><span>{t('{{booked}} of {{capacity}} spots booked',{booked:number(data.booked),capacity:number(data.capacity)})}</span></div>{state.user.role!=='member'&&<><h3>{t("Participants")}</h3>{state.bookings.filter(b=>b.classId===data.id&&b.status!=='cancelled').map(b=><div className="detail-row" key={b.id}><span><bdi>{state.members.find(m=>m.id===b.memberId)?.name}</bdi></span><Status value={b.status}/></div>)}{!state.bookings.some(b=>b.classId===data.id&&b.status!=='cancelled')&&<p className="quiet">{t("No participants yet.")}</p>}</>}{state.user.role!=='trainer'&&!booked&&new Date(data.startsAt)>new Date()&&data.booked<data.capacity?<>{state.user.role!=='member'&&<Field label={t("Book for a member")}>{memberSelect()}</Field>}<p className="form-note">{t('Booking reserves one class credit. Cancel at least {{hours}} hours before the session to return your credit.',{hours:number(state.settings.cancellationHours)})}</p>{actions}</>:<div className="form-note">{booked?t('You’re booked in. Manage your booking from Schedule.'):data.booked>=data.capacity?t("This session is full."):t("View session participants and manage attendance from Schedule.")}</div>}</>}
    {type==='checkin'&&<><Field label={t("Member")}>{memberSelect()}</Field><p className="form-note">{t("The member must have an active membership with gym access. One check-in per member per day.")}</p></>}
    {type==='confirmPayment'&&<><p>{t('Confirm you have received {{amount}} in cash from {{name}}.',{amount:money(data.amount,data.currency),name:state.members.find(m=>m.id===data.memberId)?.name})}</p><p className="form-note">{t('This records the payment and activates the {{plan}} membership.',{plan:data.description})}</p></>}
    {type==='cancel'&&<><p>{t("Cancel this reservation?")}</p><p className="form-note">{t('Your credit will be returned if this is at least {{hours}} hours before the session. Later cancellations use the credit.',{hours:number(state.settings.cancellationHours)})}</p></>}
    {type==='markAttendance'&&<Field label={t("Attendance")}><select name="status"><option value="attended">{t("Attended")}</option><option value="no-show">{t("No-show")}</option></select></Field>}
    {type!=='classDetail'&&actions}
  </form></Modal>;
}
