import {useState} from 'react';
import {Button,Modal,Field,Status,Avatar,Empty} from './ui';
import {money,date} from '../api';
export default function Dialogs({dialog,state,close,act,open}){
  const {type,data={}}=dialog;const [busy,setBusy]=useState(false);const [error,setError]=useState('');
  const titles={member:'Add a member',memberDetail:'Member profile',plan:'Create a membership plan',purchase:'Start a membership',class:'Schedule a session',classDetail:'Session details',checkin:'Check in a member',staff:'Add a team member',receipt:'Payment receipt',confirmPayment:'Confirm cash payment',cancel:'Cancel booking',markAttendance:'Record attendance'};
  const memberSelect=(defaultValue=data.memberId)=><select name="memberId" required defaultValue={defaultValue||state.user.memberId||''}><option value="" disabled>Select a member</option>{state.members.map(m=><option value={m.id} key={m.id}>{m.name}</option>)}</select>;
  async function submit(e){e.preventDefault();setError('');setBusy(true);const f=Object.fromEntries(new FormData(e.currentTarget));let path,body=f;
    if(type==='member')path='/members';
    if(type==='staff')path='/team';
    if(type==='plan'){path='/plans';body={...f,price:Math.round(Number(f.price)*100),days:Number(f.days),credits:Number(f.credits),gymAccess:f.gymAccess==='on',classes:f.classes==='on'};}
    if(type==='purchase'){path='/purchases';if(state.user.role==='member')body.memberId=state.user.memberId;}
    if(type==='class'){path='/schedule';body={...f,startsAt:new Date(f.startsAt).toISOString(),capacity:Number(f.capacity),duration:Number(f.duration)};}
    if(type==='classDetail'){path='/bookings';body={memberId:state.user.role==='member'?state.user.memberId:f.memberId,classId:data.id};}
    if(type==='checkin')path='/attendance';
    if(type==='confirmPayment'){path='/payments/'+data.id+'/confirm';body={};}
    if(type==='cancel'){path='/bookings/'+data.id+'/cancel';body={};}
    if(type==='markAttendance')path='/bookings/'+data.id+'/attendance';
    const result=await act(path,body,type==='purchase'?'Purchase created. Payment confirmation activates the membership.':'Changes saved.',null,'POST',true);
    if(result.error)setError(result.error);else close();setBusy(false);
  }
  const actions=<div className="form-actions"><Button type="button" onClick={close}>Cancel</Button><Button variant={type==='cancel'?'danger':'primary'} disabled={busy}>{busy?'Saving…':({member:'Add member',staff:'Create account',plan:'Create plan',purchase:'Create purchase',class:'Schedule session',classDetail:'Book session',checkin:'Check in',confirmPayment:'Confirm payment received',cancel:'Cancel booking',markAttendance:'Save attendance'})[type]}</Button></div>;
  if(type==='receipt')return <Modal title={titles[type]} onClose={close}><div className="receipt"><strong className="receipt-brand">FORMA.</strong><p>{state.settings.name}</p><Status value="paid"/><h2>{money(data.amount,data.currency)}</h2><dl><dt>Member</dt><dd>{state.members.find(m=>m.id===data.memberId)?.name}</dd><dt>Membership</dt><dd>{data.description}</dd><dt>Payment method</dt><dd>{data.method}</dd><dt>Paid on</dt><dd>{date(data.paidAt,{year:'numeric'})}</dd><dt>Reference</dt><dd className="reference">{data.id}</dd></dl><p className="form-note">Payment acknowledgement. This is not a tax invoice.</p></div><div className="form-actions"><Button onClick={close}>Close</Button><Button variant="primary" onClick={()=>window.print()}>Print receipt</Button></div></Modal>;
  if(type==='memberDetail'){const memberships=state.memberships.filter(m=>m.memberId===data.id);return <Modal title={titles[type]} onClose={close}><div className="profile-detail"><Avatar name={data.name}/><h3>{data.name}</h3><p>{data.email}</p><p>{data.phone||'No phone number'}</p></div><h3>Membership history</h3>{memberships.map(m=><div className="detail-row" key={m.id}><div><strong>{m.planName}</strong><small>{date(m.startsAt)} – {date(m.endsAt)}{m.classes?' · '+m.credits+' credits':''}</small></div><Status value={m.status}/></div>)}{!memberships.length&&<Empty>No membership yet.</Empty>}<div className="form-actions"><Button onClick={()=>open('checkin',{memberId:data.id})}>Check in</Button><Button variant="primary" onClick={()=>open('purchase',{memberId:data.id})}>Assign / renew plan</Button></div></Modal>;}
  const booked=type==='classDetail'&&state.bookings.some(b=>b.classId===data.id&&b.memberId===state.user.memberId&&b.status!=='cancelled');
  return <Modal title={titles[type]} onClose={close}><form onSubmit={submit}>{error&&<div className="form-error" role="alert">{error}</div>}
    {['member','staff'].includes(type)&&<><div className="form-grid"><Field label="Full name"><input autoFocus name="name" required maxLength="120" placeholder="e.g. Jordan Taylor"/></Field><Field label="Email address"><input name="email" type="email" required placeholder="jordan@example.com"/></Field><Field label="Phone number (optional)"><input name="phone" type="tel" maxLength="40" placeholder="+1 555 010 1234"/></Field>{type==='staff'&&<><Field label="Role"><select name="role"><option value="trainer">Trainer</option><option value="receptionist">Receptionist</option></select></Field><Field label="Initial password"><input name="password" type="password" required minLength="10" maxLength="128" autoComplete="new-password"/></Field></>}</div>{type==='member'&&<p className="form-note">Create the profile first, then assign a membership from the member’s profile.</p>}</>}
    {type==='plan'&&<div className="form-grid"><Field label="Plan name"><input name="name" required maxLength="120"/></Field><Field label="Type"><select name="kind"><option value="time">Time-based</option><option value="sessions">Session pack</option><option value="combined">Combined</option></select></Field><Field label={'Price ('+state.settings.currency+')'}><input name="price" type="number" step="0.01" min="1" required/></Field><Field label="Validity (days)"><input name="days" type="number" min="1" max="730" defaultValue="30" required/></Field><Field label="Session credits"><input name="credits" type="number" min="0" max="1000" defaultValue="0" required/></Field><Field label="Description"><input name="description" maxLength="250" required/></Field><label className="checkbox"><input name="gymAccess" type="checkbox" defaultChecked/>Includes gym access</label><label className="checkbox"><input name="classes" type="checkbox"/>Includes class bookings</label></div>}
    {type==='purchase'&&<><div className="form-grid">{state.user.role!=='member'&&<Field label="Member">{memberSelect()}</Field>}<Field label="Membership plan"><select name="planId" required defaultValue={data.planId||''}><option value="" disabled>Select a plan</option>{state.plans.map(p=><option value={p.id} key={p.id}>{p.name} · {money(p.price,state.settings.currency)}</option>)}</select></Field><Field label="Payment method"><select name="method"><option value="cash">Cash at reception</option><option value="online" disabled={!state.onlineEnabled}>Online payment{!state.onlineEnabled?' (not connected)':''}</option></select></Field></div><p className="form-note">Membership starts once payment is confirmed. Cash payments are confirmed by staff from Payments. Online purchases continue to checkout from Payments.</p></>}
    {type==='class'&&<div className="form-grid"><Field label="Session title"><input name="title" required maxLength="120"/></Field><Field label="Session type"><select name="type"><option>Group class</option><option>Personal training</option></select></Field><Field label="Trainer"><select name="trainerId" required><option value="">Choose a trainer</option>{state.users.filter(u=>u.role==='trainer').map(u=><option key={u.id} value={u.id}>{u.name}</option>)}</select></Field><Field label="Date & time (your device timezone)"><input name="startsAt" type="datetime-local" required/></Field><Field label="Duration (minutes)"><input name="duration" type="number" min="15" max="240" defaultValue="50" required/></Field><Field label="Capacity (personal training uses 1)"><input name="capacity" type="number" min="1" max="200" defaultValue="12" required/></Field><Field label="Room"><input name="room" required defaultValue="Studio A"/></Field></div>}
    {type==='classDetail'&&<><h3>{data.title}</h3><div className="session-details"><span>{date(data.startsAt,{weekday:'short',hour:'2-digit',minute:'2-digit',timeZone:state.settings.timezone})}</span><span>{data.duration} minutes · {data.room}</span><span>{state.users.find(u=>u.id===data.trainerId)?.name}</span><span>{data.booked} of {data.capacity} spots booked</span></div>{state.user.role!=='member'&&<><h3>Participants</h3>{state.bookings.filter(b=>b.classId===data.id&&b.status!=='cancelled').map(b=><div className="detail-row" key={b.id}><span>{state.members.find(m=>m.id===b.memberId)?.name}</span><Status value={b.status}/></div>)}{!state.bookings.some(b=>b.classId===data.id&&b.status!=='cancelled')&&<p className="quiet">No participants yet.</p>}</>}{state.user.role!=='trainer'&&!booked&&new Date(data.startsAt)>new Date()&&data.booked<data.capacity?<>{state.user.role!=='member'&&<Field label="Book for a member">{memberSelect()}</Field>}<p className="form-note">Booking reserves one class credit. Cancel at least {state.settings.cancellationHours} hours before the session to return your credit.</p>{actions}</>:<div className="form-note">{booked?'You’re booked in. Manage your booking from Schedule.':data.booked>=data.capacity?'This session is full.':'View session participants and manage attendance from Schedule.'}</div>}</>}
    {type==='checkin'&&<><Field label="Member">{memberSelect()}</Field><p className="form-note">The member must have an active membership with gym access. One check-in per member per day.</p></>}
    {type==='confirmPayment'&&<><p>Confirm you have received <strong>{money(data.amount,data.currency)}</strong> in cash from <strong>{state.members.find(m=>m.id===data.memberId)?.name}</strong>.</p><p className="form-note">This records the payment and activates the {data.description} membership.</p></>}
    {type==='cancel'&&<><p>Cancel this reservation?</p><p className="form-note">Your credit will be returned if this is at least {state.settings.cancellationHours} hours before the session. Later cancellations use the credit.</p></>}
    {type==='markAttendance'&&<Field label="Attendance"><select name="status"><option value="attended">Attended</option><option value="no-show">No-show</option></select></Field>}
    {type!=='classDetail'&&actions}
  </form></Modal>;
}
