import {useEffect,useRef,useState} from 'react';
import jsQR from 'jsqr';
import {Modal,Button} from './ui';
export default function QrScanner({close,act}){
  const video=useRef(null),stream=useRef(null),timer=useRef(null),mounted=useRef(true),generation=useRef(0),locked=useRef(false);
  const [busy,setBusy]=useState(false),[active,setActive]=useState(false),[error,setError]=useState(''),[result,setResult]=useState(null);
  function stop(){generation.current++;clearTimeout(timer.current);stream.current?.getTracks().forEach(track=>track.stop());stream.current=null;if(mounted.current)setActive(false);}
  useEffect(()=>{mounted.current=true;const visibility=()=>{if(document.hidden)stop();};document.addEventListener('visibilitychange',visibility);start();return()=>{mounted.current=false;document.removeEventListener('visibilitychange',visibility);stop();};},[]);
  async function submit(token){if(locked.current)return;locked.current=true;stop();setBusy(true);setError('');setResult(null);try{const response=await act('/attendance/scan',{token:token.trim()},'Member checked in',undefined,'POST',true);if(mounted.current){if(response.error)setError(response.error);else setResult(response);}}finally{locked.current=false;if(mounted.current)setBusy(false);}}
  async function start(){if(locked.current)return;stop();setError('');setResult(null);setBusy(true);const version=generation.current;
    try{if(!navigator.mediaDevices?.getUserMedia)throw new Error('Camera access requires HTTPS or localhost. Use manual check-in from Attendance instead.');const media=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:'environment'}},audio:false});if(!mounted.current||version!==generation.current){media.getTracks().forEach(t=>t.stop());return;}stream.current=media;video.current.srcObject=media;await video.current.play();if(!mounted.current||version!==generation.current)return;setActive(true);
      const canvas=document.createElement('canvas'),context=canvas.getContext('2d',{willReadFrequently:true});
      const scan=()=>{if(!mounted.current||version!==generation.current)return;try{if(video.current.readyState>=2){const scale=Math.min(1,720/video.current.videoWidth);canvas.width=Math.round(video.current.videoWidth*scale);canvas.height=Math.round(video.current.videoHeight*scale);context.drawImage(video.current,0,0,canvas.width,canvas.height);const pixels=context.getImageData(0,0,canvas.width,canvas.height);const code=jsQR(pixels.data,pixels.width,pixels.height,{inversionAttempts:'dontInvert'});if(code){submit(code.data);return;}}timer.current=setTimeout(scan,250);}catch{stop();setError('Could not read the camera. Try again or use manual check-in from Attendance.');}};scan();
    }catch(e){if(mounted.current&&version===generation.current){stop();setError(e.name==='NotAllowedError'?'Camera permission was denied. Allow camera access in your browser settings, then try again.':e.message);}}finally{if(mounted.current&&!locked.current)setBusy(false);}}
  return <Modal title="Scan member QR" onClose={close}><p>Point the camera at the member?s current QR code. A valid scan records the visit automatically.</p>{error&&<p role="alert" className="form-error">{error}</p>}{result&&<div className="qr-success" role="status"><strong>{result.member.name} checked in.</strong><p>{result.monthlyAttendance} gym visits this month.</p></div>}<video ref={video} muted playsInline className={'qr-camera '+(active?'is-active':'')} aria-label="QR scanner camera preview"/>{busy&&<p role="status">Opening camera or processing scan?</p>}<div className="notification-actions">{active?<Button onClick={stop}>Stop camera</Button>:!busy&&<Button variant="primary" onClick={start}>{result?'Scan next member':error?'Try camera again':'Resume camera'}</Button>}</div></Modal>;
}
