import {useEffect,useRef,useState} from 'react';
import {House,Users,Contact,CalendarDays,SquareCheck,Wallet,Settings,ArrowUpRight,LogOut,Dumbbell,Building2,Bell,Menu,X} from 'lucide-react';
import {Avatar,Button} from './ui';
const links=[['overview','Overview',House],['members','Members',Users],['memberships','Memberships',Contact],['schedule','Schedule',CalendarDays],['attendance','Attendance',SquareCheck],['payments','Payments',Wallet],['notifications','Notifications',Bell],['invitations','Invitations',Contact],['reports','Reports',Wallet],['audit','Audit log',SquareCheck],['team','Team',Users],['settings','Settings',Settings],['profile','My profile',Contact]];
export default function Shell({state,page,navigate,onLogout,onSwitch,children}){
  const member=state.user.role==='member',trainer=state.user.role==='trainer';
  const [mobileOpen,setMobileOpen]=useState(false),drawer=useRef(null);
  const visible=member?links.filter(l=>['overview','memberships','schedule','attendance','payments','notifications','profile'].includes(l[0])):trainer?links.filter(l=>['overview','schedule'].includes(l[0])):links.filter(l=>l[0]!=='profile'&&(state.user.role==='owner'||!['team','settings','reports','audit'].includes(l[0])));
  useEffect(()=>{if(mobileOpen)drawer.current.showModal();else drawer.current.close();},[mobileOpen]);
  useEffect(()=>{setMobileOpen(false);},[page,state.user.id]);
  useEffect(()=>{const media=window.matchMedia('(min-width:701px)');const changed=()=>{if(media.matches)setMobileOpen(false);};media.addEventListener('change',changed);return()=>media.removeEventListener('change',changed);},[]);
  useEffect(()=>{if(!mobileOpen)return;const previous=document.body.style.overflow;document.body.style.overflow='hidden';return()=>{document.body.style.overflow=previous;};},[mobileOpen]);
  const brand=<a className="brand" href="#overview" onClick={()=>setMobileOpen(false)} aria-label="Forma home"><Dumbbell size={29} strokeWidth={2.7}/><span>FORMA<span className="brand-dot">.</span></span></a>;
  const navigation=(mobile=false)=><nav aria-label={mobile?'Mobile navigation':'Main navigation'}>{visible.map(([key,label,Icon])=><a key={key} href={'#'+key} onClick={()=>setMobileOpen(false)} className={page===key?'active':''} aria-current={page===key?'page':undefined}><Icon size={19} strokeWidth={1.8}/>{member&&key==='overview'?'My overview':label}</a>)}</nav>;
  const profile=<div className="profile"><Avatar name={state.user.name} photo={state.members.find(m=>m.id===state.user.memberId)?.photo}/><div><strong>{state.user.name}</strong><small>{state.user.role}</small></div><button className="icon-button" onClick={()=>{setMobileOpen(false);onLogout();}} aria-label="Sign out"><LogOut size={17}/></button></div>;
  const unread=(state.notifications||[]).filter(n=>!n.readAt).length;
  return <div className="app-shell"><aside className="sidebar">{brand}{navigation()}<div className="sidebar-bottom"><div className="workspace"><Building2 size={18}/><span>{state.demo?'Demo workspace':state.settings.name}</span><span className="live-dot"/></div>{profile}</div></aside>
    <dialog ref={drawer} id="mobile-navigation" className="mobile-drawer" aria-label="Navigation menu" onCancel={()=>setMobileOpen(false)} onClose={()=>setMobileOpen(false)} onClick={e=>{if(e.target===e.currentTarget)setMobileOpen(false);}}><div className="drawer-heading">{brand}<button className="icon-button" aria-label="Close navigation" onClick={()=>setMobileOpen(false)}><X size={20}/></button></div>{navigation(true)}<div className="drawer-profile">{profile}</div></dialog>
    <div className="main-wrap"><header className="topbar"><button className="icon-button mobile-menu-button" aria-label="Open navigation" aria-controls="mobile-navigation" aria-expanded={mobileOpen} onClick={()=>setMobileOpen(true)}><Menu size={22}/></button><div className="breadcrumb">{member?'Member portal':'Workspace'}<span>/</span><strong>{visible.find(l=>l[0]===page)?.[1]||'Overview'}</strong></div><div className="topbar-actions">{state.demo?<Button onClick={onSwitch}><ArrowUpRight size={16}/>{member?'Staff workspace':'Member portal'}</Button>:<span className="quiet">{state.settings.name}</span>}{member&&<button className="icon-button notification-bell" onClick={()=>navigate('notifications')} aria-label={`Notifications, ${unread} unread`}><Bell size={19}/><span className="notification-count">{unread||''}</span></button>}</div></header><main>{children}</main><footer>{state.settings.name}<span>{state.demo?'Demo data - Changes are saved locally':'Your daily operations, connected.'}</span></footer></div></div>;
}
